### ISSUE TITLE
Fork byteball Tortik

### ISSUE THREAD

**Issue by twepl** [byteball/ocore#244]
Hello, we with the community want to create a tortik coin cryptocurrency, we still choose which cryptocurrency to choose. But your cryptocurrency suits us, can you help us fork?
https://miningclub.info/threads/tkc-tortik.65190/#post-1649179

For you, it will be like free PR in Russia

**Comment by tarmo888** [comment]
You don't need to fork Obyte when you just need to create an asset, you can create asset on mainnet through ghat interface https://asset.obyte.app/

On testnet you can create asset with that script
https://developer.obyte.org/issuing-assets-on-byteball or use AAs to create assets https://testnet.oscript.org/

**Comment by twepl** [comment]
Я по русски напишу напишу,
Если не формать то это получиться токен разве нет?
Я бы хотел совершенно другую вилку сделать, возможно внести какие то серьезные изменения.
Я собираюсь изучить код и полный функционал этой криптовалюты.
Конечно я бы не хотел делать полный форк без получения новых обновлений с вашей ветки, мне важно получать обновления. Я вижу что у вас после каждого обновления обнаруживается уязвимости.

**Comment by tarmo888** [comment]
If you want to own network just for testing then launching devnet on your own machine is probably the easiest https://github.com/pmiklos/obyte-devnet

Otherwise, launching your own mainnet will need little bit more understanding how everything works together, better start with learning about with devnet first.

If you just need a new asset then you don't need to fork it. Forking would make sense only when you feel like you could resolve any issues yourself on your network.

**Comment by twepl** [comment]
Меня еще интересует одни вопрос, если сервер упадет полностью и останутся только пользователи с кошельками, криптовалюта выживет без сервера?

**Comment by tarmo888** [comment]
That's not how cryptocurrencies work, Obyte network has hundreds of full nodes that run the same code and have a copy of the same ledger.

If you fork Obyte then you need also other full nodes that run code for your network, so single server going down wouldn't affect the users.

If you make an asset on existing Obyte network without forking then you don't have to worry about full nodes because there are already many.

**Comment by twepl** [comment]
Если я сделаю актив внутри сети Obyte могу ли я как то убрать скачивания всех блоков Obyte для своего кошелька?

**Comment by tarmo888** [comment]
Only full nodes need all transactions, Light wallets doesn't download all the data. Light wallets only have data, which is relevant to light wallet user.

**Comment by twepl** [comment]
Спасибо
